// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChd0_t7z8gdC3M2iX5XsX9iiTUcz41hUQ',
    appId: '1:97794578621:web:cdd79d301cd243ba3f7fd4',
    messagingSenderId: '97794578621',
    projectId: 'track-it-2403a',
    authDomain: 'track-it-2403a.firebaseapp.com',
    storageBucket: 'track-it-2403a.firebasestorage.app',
    measurementId: 'G-3PWXP2WZB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjZWm5gM43elB3yFzuP242_HlTMJ3_zs',
    appId: '1:97794578621:android:25a753a216840dbe3f7fd4',
    messagingSenderId: '97794578621',
    projectId: 'track-it-2403a',
    storageBucket: 'track-it-2403a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8he1sblWLkm_n37w5pY3d_KrHWMlMjmw',
    appId: '1:97794578621:ios:306cc27492a67f7e3f7fd4',
    messagingSenderId: '97794578621',
    projectId: 'track-it-2403a',
    storageBucket: 'track-it-2403a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8he1sblWLkm_n37w5pY3d_KrHWMlMjmw',
    appId: '1:97794578621:ios:306cc27492a67f7e3f7fd4',
    messagingSenderId: '97794578621',
    projectId: 'track-it-2403a',
    storageBucket: 'track-it-2403a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChd0_t7z8gdC3M2iX5XsX9iiTUcz41hUQ',
    appId: '1:97794578621:web:b22944d79c8d20743f7fd4',
    messagingSenderId: '97794578621',
    projectId: 'track-it-2403a',
    authDomain: 'track-it-2403a.firebaseapp.com',
    storageBucket: 'track-it-2403a.firebasestorage.app',
    measurementId: 'G-CMLEVEQ40W',
  );
}
