name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        # Use the exact version from your local machine
        flutter-version: '3.35.6'
    
    - name: Install dependencies
      run: |
        flutter --version
        flutter pub get
    
    - name: Build web app
      run: flutter build web --release --base-href "/expense_tracker/"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web